server:
  port: 8080
  servlet:
    context-path: /
  tomcat:
    uri-encoding: utf-8
    # tomcat 最大线程数，默认值为200
    max-threads: 200
    min-spare-threads: 20

spring:
  thymeleaf:
    mode: HTML
    encoding: UTF-8
    cache: true
  profiles:
    active: druid
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/selected-crm?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior
      =convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: 000


