server:
  port: 8080
  servlet:
    context-path: /
  tomcat:
    uri-encoding: utf-8
    # tomcat 最大线程数，默认值为200
    max-threads: 200
    min-spare-threads: 20


spring:
  thymeleaf:
    mode: HTML
    encoding: UTF-8
    cache: true
  profiles:
    active: druid

#mybatis配置
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.shinetech.crm.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml
